parserOptions:
  ecmaVersion: 2021
  sourceType: module

extends:
  - alloy
  - alloy/typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jest/recommended

env:
  browser: false
  es2021: true
  jest: true
  node: false

plugins:
  - '@typescript-eslint'
  - jest
  - promise

rules:
  import/no-unresolved: off
